SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT(S.USER_ID)) USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
GROUP BY 1, 2, 3
HAVING U.GENDER IS NOT NULL
ORDER BY 1, 2, 3
