# # SELECT DATE_FORMAT(START_DATE,'%m') MONTH, CAR_ID, COUNT(START_DATE) RECORDS
# SELECT *, COUNT(START_DATE) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
# GROUP BY CAR_ID
# # GROUP BY CAR_ID, DATE_FORMAT(START_DATE,'%m')
# HAVING COUNT(START_DATE) >= 5
# ORDER BY DATE_FORMAT(START_DATE,'%m'), CAR_ID DESC

SELECT DATE_FORMAT(START_DATE,'%m') MONTH, CAR_ID, COUNT(START_DATE) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
            GROUP BY CAR_ID
            HAVING COUNT(START_DATE) >= 5
            )
    AND DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID, DATE_FORMAT(START_DATE,'%m')
ORDER BY DATE_FORMAT(START_DATE,'%m'), CAR_ID DESC