SELECT HOUR, IFNULL(COUNT,"0") AS COUNT
FROM 
(SELECT @N:=@N+1 AS HOUR
 FROM ANIMAL_OUTS, (SELECT @N:=-1 FROM DUAL) NN
 LIMIT 24
) T
LEFT JOIN 
(SELECT DATE_FORMAT(DATETIME, '%k') HR, COUNT(*) COUNT
FROM ANIMAL_OUTS 
GROUP BY DATE_FORMAT(DATETIME, '%k')
ORDER BY DATE_FORMAT(DATETIME, '%H')
) A
ON T.HOUR = A.HR