-- 코드를 입력하세요
SELECT B.CATEGORY '카테고리(CATEGORY)', SUM(S.SALES) '총 판매량(TOTAL_SALES)'
FROM BOOK B
RIGHT JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY