-- 코드를 입력하세요
# SELECT H.CAR_ID, MAX(H.AVAIL) AVAILABILITY
# FROM (SELECT *, CASE 
#                     WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
#                     ELSE '대여 가능'
#                 END AVAIL
#      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H
# GROUP BY H.CAR_ID
# ORDER BY H.CAR_ID DESC

SELECT
CAR_ID,
MAX(IF("2022-10-16" BETWEEN START_DATE AND END_DATE, "대여중", "대여 가능")) AS AVAILABILITY
FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
CAR_ID
ORDER BY
CAR_ID DESC