-- 10:52 ~ 11:10-12:44 ~  --



# FROM(
#     SELECT *, DATEDIFF(END_DATE, START_DATE)
#     FROM CAR_RENTAL_COMPANY_CAR C
#     NATURAL JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#     WHERE C.CAR_TYPE = '트럭') A

SELECT HISTORY_ID, FEE
FROM (
    SELECT HISTORY_ID, CAR_ID, DAILY_FEE, DIFF, MAX(DC) MYDISCOUNT, ROUND(DAILY_FEE*(1-MAX(DC)*0.01)*DIFF) FEE
    FROM (SELECT CAR_ID, DAILY_FEE, HISTORY_ID, DATEDIFF(END_DATE, START_DATE)+1 DIFF, PLAN_ID, REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '') DR, DISCOUNT_RATE
        , (CASE
               WHEN DATEDIFF(END_DATE, START_DATE) >= REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '') 
                THEN DISCOUNT_RATE
               ELSE 0
           END
           ) DC
        FROM CAR_RENTAL_COMPANY_CAR C
        NATURAL JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P USING (CAR_TYPE)
        WHERE C.CAR_TYPE = '트럭') RES1
    GROUP BY HISTORY_ID
    ORDER BY FEE DESC, 1 DESC
    ) RES2