SELECT T1.APNT_NO, P.PT_NAME, T1.PT_NO, T1.MCDP_CD, D.DR_NAME, T1.APNT_YMD
FROM (SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
      FROM APPOINTMENT
      WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'
     ) T1
JOIN PATIENT P USING (PT_NO)
JOIN DOCTOR D ON D.DR_ID = T1.MDDR_ID
ORDER BY T1.APNT_YMD 